# Site settings
title: I1820
description: "Good Days, Good Things"
repository: "I1820/I1820.github.io"

# Secondary Parameters
header-img: img/header.jpg
headercolor: "#FFFFFF"
logo: img/logo.png

# Tertiary Parameters
github_username: I1820
project_repository: I1820.github.io

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
exclude:
  - less
  - node_modules
  - Gruntfile.js
  - package.json
  - README.md
